### ISSUE TITLE
running the pretrained models on single WAV files

### ISSUE THREAD

**Issue by ajitzote** [nicklashansen/voice-activity-detection#3]
hey man, if we just want to run the pre-trained models on our WAV file, how can we do that? and can you provide a tutorial to run these models on single WAV files(around 6 seconds of duration).

**Comment by kli017** [comment]
hello do you figure out how to using the model?

**Comment by ajitzote** [comment]
Hello , not yet.

**Comment by ajitzote** [comment]
> hello do you figure out how to using the model?

**Comment by ajitzote** [comment]
> hello do you figure out how to using the model?

not yet, do let me know if you could run it first, I will let you know if I could do it.

**Comment by ajitzote** [comment]
> hello do you figure out how to using the model?

i was able to run it on my wav file finally! took me 1 week lol XD

**Comment by hetpandya** [comment]
Hi @ajitzote , how did you manage to run on the wav file?

**Comment by ajitzote** [comment]
First copy the file in the speech folder atleast 2-3 thousand times. And
then run the code without adding noise to the speech file. You will not get
the quantitative results but you will get qualitative results

**Comment by hetpandya** [comment]
Thanks a lot! I shall check it out.

**Comment by ajitzote** [comment]
welcome.message me on facebook if you need more help, search Ajit Zote
!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
